baseURL: "https://vidushikhanna.netlify.app/"
languageCode: en-uk
title: Vidushi Khanna
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 40
    - identifier: experiences
      name: Experience
      url: /experience
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 60
    - identifier: tags
      name: Tags
      url: /tags
      weight: 70
    - identifier: certifications
      name: Certifications and Skills
      url: /certifications/
      weight: 30
    

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Vidushi Khanna"
    subtitle: Technical Solutions Analyst 🧑🏻‍💻 at [**Oracle Cerner**](https://www.cerner.com/), a leading healthcare IT organisation providing data-backed health technology solutions, USA.<br>A Dental graduate(BDS) with passion for all things **Digital**, **Data driven**, and requiring a deep dive into **analysis**, from India.<br>
    imageUrl: "home/image4.jpeg"
    imageWidth: 210
    imageHeight: 240
    # buttons:
    #   - name: Resume
    #     url: "https://drive.google.com/file/d/1XH38cy9Gjal_GK04OHLUr6UqoLVDbSf8/view?usp=sharing"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "Email"
      url: "mailto:vidushi04.khanna@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/dr-vidushi-khanna/"
    - name: "Github"
      url: "https://github.com/vidushi101"
    - name: "Kaggle"
      url: "https://www.kaggle.com/vidushikhanna"
    - name: "CV"
      url: "https://drive.google.com/file/d/1qWEWph-a-DFqNaLsG0pzfNtDcZBW_5ht/view?usp=drive_link"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
